name: Tinylnk Backend CI/CD

on:
  push:
    branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22',
          cache: 'npm'

      - name: Setup dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install pm2 on server
        run: npm i -g pm2

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd /home/repositories/tinylnk/backend
            git pull origin main
            npm install
            npm run build
            pm2 restart tinylnk-backend